/**
 * varaTheme.ts
 * ─────────────────────────────────────────────────────────────────
 * Vara dizajn sustav — zamjena za sve StyleSheet objekte u dashboard.tsx
 * Uvezi ovaj fajl i zamijeni lokalne style objekte s ovim exportima.
 *
 * NEMA PROMJENA LOGIKE — isključivo vizualni sloj.
 *
 * Paleta boja:
 *   Forest deep:   #1A2E15   (pozadina, glavna)
 *   Forest mid:    #243B1E   (kartice, inputi)
 *   Forest light:  #2D5518   (hover, sekundarne površine)
 *   Border green:  #4A7040   (rubovi, separator)
 *   Silver:        #C4CABC   (tekst, ikone)
 *   Silver bright: #E8EDE4   (naslovi, aktivni tekst)
 *   Silver dim:    #8A9486   (hint tekst, meta)
 *   Accent gold:   #B8A060   (premium akcent, oznake)
 *   Visited:       #5A8A48   (posjećeno)
 *   Danger:        #8B3030   (ukloni, skriveno)
 *   Overlay:       rgba(10,20,8,0.88)
 * ─────────────────────────────────────────────────────────────────
 */

import { Dimensions, Platform, StyleSheet } from "react-native";

const { width: SW, height: SH } = Dimensions.get("window");

// ── Paleta ────────────────────────────────────────────────────────
export const V = {
  forestDeep: "#1A2E15",
  forestMid: "#243B1E",
  forestLight: "#2D5518",
  borderGreen: "#4A7040",
  borderDim: "#304A28",
  silver: "#C4CABC",
  silverBright: "#E8EDE4",
  silverDim: "#8A9486",
  accentGold: "#B8A060",
  visited: "#5A8A48",
  visitedLight: "#3D6B32",
  danger: "#8B3030",
  overlay: "rgba(10,20,8,0.88)",
  overlayLight: "rgba(26,46,21,0.92)",
  cardBg: "#1E3418",
  inputBg: "#243B1E",
  chipBg: "#1E3418",
  chipActive: "#3D6B32",
  white: "#F0F4EE",
} as const;

// ── Marker stilovi (zamjena za `ms`) ──────────────────────────────
export const ms = StyleSheet.create({
  circle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: V.borderGreen,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.55,
    shadowRadius: 5,
    elevation: 8,
  },
  emoji: { fontSize: 22 },
  pin: {
    width: 5,
    height: 12,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginTop: -2,
  },
});

// ── Progress bar (zamjena za `pb`) ────────────────────────────────
export const pb = StyleSheet.create({
  track: {
    height: 4,
    backgroundColor: V.borderDim,
    borderRadius: 2,
    overflow: "hidden",
    marginTop: 12,
  },
  fill: {
    height: "100%",
    backgroundColor: V.visited,
    borderRadius: 2,
  },
});

// ── Place Detail Modal (zamjena za `dm`) ──────────────────────────
export const dm = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: V.overlay,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: V.forestDeep,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1.5,
    borderColor: V.borderGreen,
    maxHeight: SH * 0.92,
  },
  imageBox: { position: "relative" },
  imgPh: {
    width: "100%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: V.forestMid,
  },
  img: { width: "100%", height: 220 },
  dots: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "rgba(196,202,188,0.3)",
  },
  dotA: { backgroundColor: V.silver },
  closeBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: V.overlay,
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  hideBtn: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: V.overlay,
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  body: { padding: 20, paddingBottom: 36 },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 6,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: V.borderGreen,
  },
  badgeTxt: { color: V.silverBright, fontSize: 13, fontWeight: "700" },
  name: {
    fontSize: 22,
    fontWeight: "800",
    color: V.silverBright,
    marginBottom: 6,
  },
  meta: { fontSize: 14, color: V.silverDim, marginBottom: 4 },
  rating: { fontSize: 15, color: V.accentGold, marginBottom: 8 },
  hoursBox: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    padding: 14,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  hoursTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: V.silver,
    marginBottom: 6,
  },
  hoursText: { fontSize: 13, color: V.silverDim, lineHeight: 20 },
  notifRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: V.forestMid,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderDim,
    padding: 14,
    marginBottom: 12,
  },
  notifLabel: { fontSize: 14, color: V.silver, fontWeight: "600", flex: 1 },
  reviewBox: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: V.borderDim,
    padding: 16,
    marginBottom: 16,
    gap: 12,
  },
  reviewTitle: { fontSize: 15, fontWeight: "700", color: V.silver },
  commentInput: {
    backgroundColor: V.forestDeep,
    borderWidth: 1,
    borderColor: V.borderGreen,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: V.silverBright,
    minHeight: 80,
    textAlignVertical: "top",
  },
  returnToggle: {
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: V.forestDeep,
    borderWidth: 1,
    borderColor: V.borderDim,
    alignSelf: "flex-start",
  },
  returnA: {
    backgroundColor: V.forestLight,
    borderColor: V.visited,
  },
  returnTxt: { fontSize: 14, color: V.silver, fontWeight: "600" },
  reviewBtn: { borderRadius: 10, paddingVertical: 12, alignItems: "center" },
  reviewBtnTxt: { color: V.silverBright, fontWeight: "700", fontSize: 15 },
  visitBtn: {
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: V.visited,
  },
  visitBtnTxt: { color: V.silverBright, fontSize: 16, fontWeight: "700" },
  visitedBadge: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: V.visited,
  },
});

// ── Activity Groups Modal (zamjena za `ag`) ───────────────────────
export const ag = StyleSheet.create({
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    paddingTop: Platform.OS === "ios" ? 54 : 36,
    backgroundColor: V.forestDeep,
    borderBottomWidth: 1.5,
    borderBottomColor: V.borderGreen,
    gap: 12,
  },
  dmOverlay: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: V.overlay,
    justifyContent: "flex-end" as const,
    zIndex: 999,
  },
  dmSheet: {
    backgroundColor: V.forestDeep,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1.5,
    borderColor: V.borderGreen,
    padding: 20,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    maxHeight: "70%",
  },
  dmHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: V.borderGreen,
    alignSelf: "center" as const,
    marginBottom: 16,
  },
  dmHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
  },
  dmAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: V.forestLight,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center" as const,
    alignItems: "center" as const,
  },
  dmTitle: { fontSize: 16, fontWeight: "700" as const, color: V.silverBright },
  dmSubtitle: { fontSize: 14, color: V.visited, marginTop: 2 },
  dmWarnBadge: {
    backgroundColor: "#2A2010",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.accentGold,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  dmInput: {
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderGreen,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    minHeight: 90,
    color: V.silverBright,
    marginBottom: 12,
  },
  dmQuickBtn: {
    backgroundColor: V.forestMid,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: V.borderDim,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  dmQuickText: { fontSize: 13, color: V.silver, fontWeight: "600" },
  dmActions: {
    flexDirection: "row" as const,
    gap: 10,
    marginTop: 4,
  },
  dmCancelBtn: {
    paddingVertical: 13,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderDim,
    alignItems: "center" as const,
  },
  dmCancelText: { color: V.silverDim, fontSize: 14, fontWeight: "600" },
  dmSendBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: V.forestLight,
    borderWidth: 1,
    borderColor: V.borderGreen,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  dmSendBtnDisabled: {
    backgroundColor: V.forestDeep,
    borderColor: V.borderDim,
  },
  dmSendText: { color: V.silverBright, fontSize: 15, fontWeight: "700" },
  chatHeaderBack: { color: V.silver, fontSize: 22 },
  chatHeaderTitle: { color: V.silverBright, fontSize: 16, fontWeight: "800" },
  chatHeaderSub: { color: V.silverDim, fontSize: 12 },
  membersRow: {
    maxHeight: 72,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
    backgroundColor: V.forestMid,
  },
  memberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: V.forestLight,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  memberAvatarEmpty: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: V.forestDeep,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: V.borderDim,
    borderStyle: "dashed",
  },
  memberName: { fontSize: 10, color: V.silverDim, marginTop: 2 },
  msgRow: { flexDirection: "row", marginVertical: 4, gap: 8 },
  msgAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: V.forestLight,
    borderWidth: 1,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  msgSender: { fontSize: 11, color: V.silverDim, marginBottom: 2 },
  bubble: { borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8 },
  bubbleMine: {
    backgroundColor: V.forestLight,
    borderBottomRightRadius: 4,
    borderWidth: 1,
    borderColor: V.borderGreen,
  },
  bubbleOther: {
    backgroundColor: V.forestMid,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  msgTime: { fontSize: 10, color: V.silverDim, marginTop: 2 },
  inputRow: {
    flexDirection: "row",
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: V.borderDim,
    gap: 8,
    backgroundColor: V.forestDeep,
  },
  input: {
    flex: 1,
    backgroundColor: V.forestMid,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: V.silverBright,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: V.forestLight,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  joinBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    paddingVertical: 14,
    alignItems: "center",
  },
  joinBtnText: { color: V.silverBright, fontSize: 16, fontWeight: "700" },
  navHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    paddingTop: Platform.OS === "ios" ? 54 : 36,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
    backgroundColor: V.forestDeep,
  },
  navHeaderLink: { fontSize: 16, color: V.silver },
  navHeaderTitle: { fontSize: 17, fontWeight: "800", color: V.silverBright },
  formLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: V.silver,
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderGreen,
    padding: 14,
    fontSize: 15,
    color: V.silverBright,
    marginBottom: 16,
  },
  templateChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  templateChipActive: {
    backgroundColor: V.forestLight,
    borderColor: V.borderGreen,
  },
  templateChipText: { fontSize: 13, fontWeight: "600", color: V.silver },
  listHeader: {
    backgroundColor: V.forestDeep,
    borderBottomWidth: 1.5,
    borderBottomColor: V.borderGreen,
    padding: 20,
    paddingTop: Platform.OS === "ios" ? 54 : 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  listHeaderTitle: { color: V.silverBright, fontSize: 18, fontWeight: "800" },
  newBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  groupCard: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderWidth: 1,
    borderColor: V.borderDim,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  groupTitle: { fontSize: 16, fontWeight: "800", color: V.silverBright },
  groupLocation: { fontSize: 13, color: V.visited, marginTop: 2 },
  groupDesc: { fontSize: 13, color: V.silverDim, marginTop: 4 },
  groupIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  groupFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  footerAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: V.forestLight,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  groupCount: {
    fontSize: 12,
    color: V.silverDim,
    fontWeight: "600",
    marginLeft: 4,
  },
  badgeOwn: {
    backgroundColor: V.forestLight,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeOwnText: { fontSize: 11, color: V.silver, fontWeight: "700" },
  badgeMember: {
    backgroundColor: V.forestLight,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: V.visited,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeMemberText: { fontSize: 11, color: V.visited, fontWeight: "700" },
  badgeFull: {
    backgroundColor: V.forestDeep,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: V.borderDim,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  joinSmallBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
});

// ── Plan My Day Modal (zamjena za `pm`) ───────────────────────────
export const pm = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: Platform.OS === "ios" ? 54 : 36,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
    backgroundColor: V.forestDeep,
  },
  headerTitle: { fontSize: 16, fontWeight: "700", color: V.silverBright },
  headerLink: {
    fontSize: 14,
    color: V.silver,
    fontWeight: "600",
    minWidth: 60,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: V.silverBright,
    marginBottom: 10,
    marginTop: 20,
  },
  label: { fontSize: 13, color: V.silverDim, marginBottom: 8 },
  input: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderGreen,
    padding: 12,
    fontSize: 15,
    color: V.silverBright,
    marginBottom: 10,
  },
  row: { flexDirection: "row", marginBottom: 0 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  chipSmall: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  chipMd: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderDim,
    alignItems: "center",
    minWidth: 64,
  },
  chipActive: {
    backgroundColor: V.forestLight,
    borderColor: V.borderGreen,
  },
  chipText: { fontSize: 13, fontWeight: "600", color: V.silver },
  chipTextActive: { color: V.silverBright },
  generateBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    paddingVertical: 18,
    alignItems: "center",
    marginTop: 8,
  },
  generateBtnText: { color: V.silverBright, fontSize: 16, fontWeight: "700" },
  generateHint: {
    textAlign: "center",
    fontSize: 12,
    color: V.silverDim,
    marginTop: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    backgroundColor: V.forestDeep,
  },
  loadingIcon: { fontSize: 64, marginTop: 24, marginBottom: 8 },
  loadingText: {
    fontSize: 18,
    fontWeight: "700",
    color: V.silverBright,
    textAlign: "center",
  },
  loadingHint: {
    fontSize: 13,
    color: V.silverDim,
    marginTop: 8,
    textAlign: "center",
  },
  resultBadge: {
    backgroundColor: V.forestMid,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 16,
    alignSelf: "flex-start",
  },
  resultBadgeText: { fontSize: 13, color: V.silver, fontWeight: "600" },
  resultText: {
    fontSize: 13,
    color: V.silver,
    lineHeight: 22,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  btnPrimary: {
    backgroundColor: V.forestLight,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    paddingVertical: 14,
    alignItems: "center",
  },
  btnPrimaryText: { color: V.silverBright, fontSize: 15, fontWeight: "700" },
  btnSecondary: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: V.borderGreen,
  },
  btnSecondaryText: { color: V.silver, fontSize: 15, fontWeight: "600" },
});

// ── Plan Renderer (zamjena za `pr`) ───────────────────────────────
export const pr = StyleSheet.create({
  container: { gap: 3, paddingBottom: 8 },
  titleBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: V.forestLight,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    padding: 18,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  titleEmoji: { fontSize: 34 },
  titleSub: {
    color: V.silverDim,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.8,
    marginBottom: 2,
  },
  titleMain: {
    color: V.silverBright,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 26,
  },
  metaCard: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: V.borderDim,
    padding: 14,
    marginBottom: 4,
    gap: 6,
  },
  metaRow: { flexDirection: "row" },
  metaText: { fontSize: 13, color: V.silver, lineHeight: 21, flex: 1 },
  dayCard: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: V.visited,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  dayText: { fontSize: 17, fontWeight: "900", color: V.silverBright },
  timeBlock: {
    borderRadius: 8,
    borderLeftWidth: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: V.forestMid,
  },
  timeText: { fontSize: 14, fontWeight: "700" },
  activityCard: {
    backgroundColor: V.forestMid,
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 14,
    marginLeft: 12,
    marginVertical: 2,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  activityText: { fontSize: 13, color: V.silver, lineHeight: 20 },
  costBox: {
    backgroundColor: "#231C0A",
    borderRadius: 8,
    padding: 12,
    marginTop: 10,
    marginLeft: 12,
    borderLeftWidth: 4,
    borderLeftColor: V.accentGold,
    borderWidth: 1,
    borderColor: "#3A2E10",
  },
  costText: { fontSize: 13, color: V.accentGold, fontWeight: "700" },
  tipsHeader: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    padding: 16,
    marginTop: 24,
    borderLeftWidth: 4,
    borderLeftColor: V.visited,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  tipsTitle: { fontSize: 16, fontWeight: "800", color: V.silverBright },
  tipRow: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingLeft: 14,
    gap: 8,
    alignItems: "flex-start",
  },
  tipDot: { fontSize: 18, color: V.visited, fontWeight: "800", lineHeight: 22 },
  tipText: { fontSize: 13, color: V.silver, lineHeight: 22, flex: 1 },
  noteBox: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    padding: 14,
    marginTop: 18,
    borderLeftWidth: 4,
    borderLeftColor: V.silver,
    borderWidth: 1,
    borderColor: V.borderDim,
  },
  noteText: { fontSize: 12, color: V.silverDim, lineHeight: 18 },
  closingBox: {
    backgroundColor: V.forestLight,
    borderRadius: 10,
    padding: 14,
    marginTop: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: V.borderGreen,
  },
  closingText: {
    fontSize: 14,
    color: V.silverBright,
    fontWeight: "700",
    textAlign: "center",
  },
});

// ── Map legend (zamjena za `mapLegend`) ───────────────────────────
export const mapLegend = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  headerTitle: { fontSize: 16, fontWeight: "800", color: V.silverBright },
  headerSub: {
    fontSize: 12,
    color: V.silverDim,
    marginTop: 2,
    maxWidth: "90%",
  },
  recenterBtn: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: V.forestMid,
    borderWidth: 1,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
  },
  legendContainer: {
    backgroundColor: V.forestMid,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderDim,
    padding: 12,
    marginBottom: 8,
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: V.silverDim,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  legendRow: { flexDirection: "row", gap: 8, paddingBottom: 2 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1.5,
  },
  dot: { width: 8, height: 8, borderRadius: 4 },
  chipText: { fontSize: 11, fontWeight: "600", color: V.silver },
  distanceSection: {
    backgroundColor: V.forestMid,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: V.borderDim,
    padding: 14,
    marginBottom: 16,
  },
  distanceTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: V.silver,
    marginBottom: 10,
  },
  distanceGrid: { gap: 8 },
  distanceChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: V.forestDeep,
    borderRadius: 8,
    padding: 10,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: V.borderDim,
    gap: 10,
  },
  distanceEmoji: { fontSize: 22 },
  distanceName: { fontSize: 13, fontWeight: "600", color: V.silver },
  distanceKm: { fontSize: 12, fontWeight: "700", marginTop: 2 },
});

// ── Plan styles (zamjena za `planStyles`) ─────────────────────────
export const planStyles = StyleSheet.create({
  progressCard: {
    backgroundColor: V.forestMid,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: V.borderGreen,
    padding: 16,
    marginBottom: 16,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  progressTitle: { fontSize: 14, fontWeight: "700", color: V.silver },
  progressCount: { fontSize: 14, fontWeight: "800", color: V.visited },
  progressTrack: {
    height: 8,
    backgroundColor: V.borderDim,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: V.visited,
    borderRadius: 4,
  },
  progressHint: {
    fontSize: 12,
    color: V.visited,
    marginTop: 8,
    fontWeight: "600",
  },
  sectionHeader: {
    fontSize: 16,
    fontWeight: "800",
    color: V.silverBright,
    marginBottom: 4,
  },
  sectionSub: { fontSize: 12, color: V.silverDim, marginBottom: 12 },
  categorySection: {
    backgroundColor: V.forestMid,
    borderRadius: 14,
    marginBottom: 16,
    borderTopWidth: 3,
    borderWidth: 1,
    borderColor: V.borderDim,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
    backgroundColor: V.forestDeep,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
  },
  categoryDot: {
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: V.borderGreen,
  },
  categoryTitle: { fontSize: 15, fontWeight: "800", color: V.silverBright },
  categorySub: { fontSize: 12, color: V.silverDim, marginTop: 2 },
  catBadge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1.5,
  },
  catBadgeText: { fontSize: 12, fontWeight: "800" },
  venueCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: V.borderDim,
    gap: 10,
    backgroundColor: V.forestMid,
  },
  venueCardVisited: { backgroundColor: "#1C301A" },
  venueName: { fontSize: 14, fontWeight: "700", color: V.silverBright },
  venueAddress: { fontSize: 11, color: V.silverDim, marginTop: 2 },
  venueDist: { fontSize: 11, fontWeight: "700", marginTop: 2 },
  venueDetailHint: { fontSize: 11, color: V.silverDim, marginTop: 2 },
  visitToggleBtn: {
    minWidth: 50, // ← smanjeno
    maxWidth: 52, // ← dodaj max
    paddingHorizontal: 6, // ← smanjeno
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  visitToggleBtnVisited: {
    backgroundColor: V.forestLight,
    borderColor: V.visited,
  },
  visitToggleText: {
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 14,
  },
  visitToggleTextVisited: {
    fontSize: 11,
    fontWeight: "800",
    color: V.visited,
    textAlign: "center",
  },
});

// ── Main screen (zamjena za `s`) ──────────────────────────────────
export const s = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  topBar: {
    position: "absolute",
    top: Platform.OS === "ios" ? 54 : 36,
    left: 12,
    right: 12,
    gap: 8,
  },
  sideIcon: {
    width: 28,
    height: 28,
    // UKLONI tintColor da zadrži originalne boje slike
    // tintColor: "#1A2E15",  // OVO JE BIO PROBLEM - ukloni!
  },
  sideIconActive: {
    // Možeš dodati efekat za aktivnu ikonu ako želiš
    // tintColor: "#fff",
  },
  sideBtnEmoji: {
    fontSize: 26,
    color: V.silverBright, // Dodaj boju za emoji
  },
  sideBtnActive: {
    backgroundColor: V.forestLight,
    borderColor: V.borderGreen,
  },
  citySearchRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: V.forestDeep,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    paddingLeft: 14,
    paddingRight: 6,
    paddingVertical: 4,
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.45,
    shadowRadius: 6,
    elevation: 8,
  },
  cityInput: {
    flex: 1,
    fontSize: 14,
    color: V.silverBright,
    paddingVertical: 8,
  },
  citySearchBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  clearCityBtn: {
    backgroundColor: "#2A1010",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#5A3030",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  remoteBadge: {
    backgroundColor: V.forestLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  topBtn: {
    backgroundColor: V.forestDeep,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    alignSelf: "flex-start",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 5,
  },
  topBtnText: { fontSize: 14, fontWeight: "600", color: V.silver },
  todBtn: {
    backgroundColor: V.forestDeep,
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  todBtnA: {
    backgroundColor: V.forestLight,
    borderColor: V.silver,
  },
  todTxt: { fontSize: 18 },

  // ── Side panel — ikone desno na karti ────────────────────────────
  sidePanel: { position: "absolute", right: 12, bottom: 60, gap: 6 },
  sideBtn: {
    backgroundColor: V.forestDeep,
    width: 46,
    height: 46,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: V.borderGreen,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 4,
    elevation: 6,
  },
  sideBtnA: {
    backgroundColor: V.forestLight,
    borderColor: V.silver,
  },
  sideBtnNotif: { backgroundColor: "#231C0A", borderColor: V.accentGold },
  sideBtnTxt: { fontSize: 20 },
  notifDot: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: V.danger,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: V.forestDeep,
  },

  // ── Loading / count bar ───────────────────────────────────────────
  loadingBar: {
    position: "absolute",
    bottom: 90,
    left: 20,
    right: 20,
    flexDirection: "row",
    backgroundColor: V.overlayLight,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    gap: 10,
    justifyContent: "center",
  },
  loadingTxt: { color: V.silver, fontSize: 14, fontWeight: "600" },
  bottomBar: {
    position: "absolute",
    bottom: 90,
    left: 20,
    right: 20,
    backgroundColor: V.overlayLight,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  countTxt: { color: V.silver, fontSize: 13, fontWeight: "600", flex: 1 },
  showMoreBtn: {
    backgroundColor: V.forestLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: V.borderGreen,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginLeft: 8,
  },
  showMoreTxt: { color: V.silverBright, fontSize: 12, fontWeight: "700" },
});
